apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myhello
  template:
    metadata:
      labels:
        app: myhello
    spec:
      containers:
        - name: myhello
          image: docker.io/yturta/my_hello:my_hello