apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-depl
spec:
  template:
    spec:
      containers:
      - name: myhello
        volumeMounts:
        - name: emptyDir
          mountPath: /appdata 
    volumes:
    - name: emptyDir
      emptyDir: {}
